### ISSUE TITLE
Getting "Need a Premium Account" Overlay

### ISSUE THREAD

**Issue by hydriniumh2** [williamtcastro/carthing-non-premium-spotify#1]
First, thanks for putting in the work to make this, it's very promising!
I ran into this issue on a freshly rooted CarThing using Superbird tool with Spotify version 8.7.86.422. I believe all steps completed correctly but I may have missed something.

After installing it on a rooted device, it allows me to pair my phone with non-premium spotify to the CarThing and access device settings etc which is definitely more than the stock CarThing (which just shows a locked welcome screen). 
However, I now get an overlay over the music playing which says:
```
   Need a Premium Account
To use Car Thing you need to be 
logged into a Spotify Premium or 
Premium Family account on your 
           phone
```
when I try to use the CarThing. The weird thing is that I can see the music playing underneath the overlay so it's definitely working, just not 100% there. 
One thing that didn't match the instructions was that there was no webapp in /usr/share/qt-superbird-app/ to save as webapp_orig just these files:
```
~/carthing-non-premium-spotify|main ⇒ adb shell ls /usr/share/qt-superbird-app/
libyobe.so
musiccmds_voice_hub_vad_en-US_v3.0_permanent.snsr
sensory-thf-enUS-heyspotify_delivery19lbu_db0a81403.snsr
sensory-thf-enUS-heyspotify_delivery21ftu_hpf500_a29a58b6e_am.snsr
sensory-thf-enUS-heyspotify_delivery22ftu_hpf750_6273e4262_am.snsr
voice_hub_3p_voice_assistants_v2.0.snsr
vui_4micLinear_CarThing_AmbiNL_v6_0.awb
```
Please let me know if there's any additional information that I can provide to help debug the issue. Thank you.

**Comment by hydriniumh2** [comment]
Ah ok figured it out from your past posts on reddit!
I was using the xmanager Spotify version but I guess the apk requires further modifications to access the CarThing correctly
As outlined here: 
https://old.reddit.com/r/carthinghax/comments/yipfvy/possible_to_hack_to_allow_nonpremium_account_use/
![image](https://user-images.githubusercontent.com/19802736/204160293-3ad38dde-c3c0-47bb-962f-00d932c86250.png)


I downloaded the modified apk and used that instead of Xmanager's version.
And now the CarThing works!
Probably would be helpful to mention the Spotify Client needs to be a special modded version in the README

**Comment by hydriniumh2** [comment]
Although I'm now realizing that I could have just installed the modded APK and gotten full access without having to mess around rooting the CarThing since I'm using an android. 🤦

**Comment by BG7FBI** [comment]
the link has expired, any luck update it?

**Comment by hydriniumh2** [comment]
Uploaded my copy of the apk to a random repo https://github.com/hydriniumh2/hello-world/releases/tag/dev

**Comment by BG7FBI** [comment]
thanks a lot, I'll give it a try.
