### ISSUE TITLE
something went wrong and carthing will reboot in few seconds

### ISSUE THREAD

**Issue by BG7FBI** [williamtcastro/carthing-non-premium-spotify#2]
**<I AM A WINDOWS 10 USER>**

Flashed jailbroken firmware provided from lmore377, and followed instructions in readme.md
After reboot the CARTHING shows a error page says went wrong and neet to reboot, then falls in reboot loop.

After poking around the file system i found out that in **step #3** commamd
`adb push webapp /usr/share/qt-superbird-app/`
will copy the files in _/webapp_ to /_qt-superbird-app_, but instead those files need to be in _/qt-superbird-app/webapp/_

If this happens, DO NOT run the commad above but instead run command:
`adb push webapp /usr/share/qt-superbird-app/webapp/`
and now you can enjoy Carthing with spotifyFREE account.

**Comment by williamtcastro** [comment]
That happened with me yesterday but I've noticed that the `/usr/share/qt-superbird-app/webapp` folder didn't exist to after the first command of step 3.

If that happens you definitely need to run this command `adb push webapp /usr/share/qt-superbird-app/webapp/`
as you pointed but make sure that the command don't point to `/usr/share/qt-superbird-app/webapp/webapp/` other wise the change won't work.

Thank you so much for pointing this issue

**Comment by BG7FBI** [comment]
Just check the file path is correct or simply verify the folder exsits.
Before reboot run commamd:
`adb shell ls /usr/share/qt-superbird-app/`

If folder _/webapp_ exists, then continue to step#4 reboot.
If not then push files again to _/usr/share/qt-superbird-app/webapp/_


This my first try:
C:\carthing\superbird-tool>adb shell mount -o remount,rw /

C:\carthing\superbird-tool>cd C:\carthing\carthing-non-premium-spotify

C:\carthing\carthing-non-premium-spotify>adb push settings/onboarding_status /var/lib/qt-superbird-app/settings
4 KB/s (9 bytes in 0.001s)

C:\carthing\carthing-non-premium-spotify>adb push settings/setup_state /var/lib/qt-superbird-app/settings
4 KB/s (9 bytes in 0.001s)

C:\carthing\carthing-non-premium-spotify>adb shell mv /usr/share/qt-superbird-app/webapp /usr/share/qt-superbird-app/webapp-orig

C:\carthing\carthing-non-premium-spotify>adb push webapp /usr/share/qt-superbird-app/
push: webapp/images/setup-qr.svg -> /usr/share/qt-superbird-app/images/setup-qr.svg
push: webapp/images/round-corners.svg -> /usr/share/qt-superbird-app/images/round-corners.svg
push: webapp/images/radio-rings-bg.svg -> /usr/share/qt-superbird-app/images/radio-rings-bg.svg
push: webapp/images/no-connection.svg -> /usr/share/qt-superbird-app/images/no-connection.svg
push: webapp/images/more-48.svg -> /usr/share/qt-superbird-app/images/more-48.svg
push: webapp/images/mobile-signal.svg -> /usr/share/qt-superbird-app/images/mobile-signal.svg
push: webapp/images/menu-dots.svg -> /usr/share/qt-superbird-app/images/menu-dots.svg
push: webapp/images/explicit.svg -> /usr/share/qt-superbird-app/images/explicit.svg
push: webapp/images/bluetooth-icon.svg -> /usr/share/qt-superbird-app/images/bluetooth-icon.svg
push: webapp/images/appstart.png -> /usr/share/qt-superbird-app/images/appstart.png
push: webapp/license/ui-license.txt -> /usr/share/qt-superbird-app/license/ui-license.txt
push: webapp/license/os-license.txt -> /usr/share/qt-superbird-app/license/os-license.txt
push: webapp/license/mw-license.txt -> /usr/share/qt-superbird-app/license/mw-license.txt
push: webapp/static/css/main.css.map -> /usr/share/qt-superbird-app/static/css/main.css.map
push: webapp/static/css/main.css -> /usr/share/qt-superbird-app/static/css/main.css
push: webapp/static/js/main.js.map -> /usr/share/qt-superbird-app/static/js/main.js.map
push: webapp/static/js/main.js.LICENSE.txt -> /usr/share/qt-superbird-app/static/js/main.js.LICENSE.txt
push: webapp/static/js/main.js -> /usr/share/qt-superbird-app/static/js/main.js
push: webapp/static/media/other-media.83237a6ee7e62a4fb53b.png -> /usr/share/qt-superbird-app/static/media/other-media.83237a6ee7e62a4fb53b.png
push: webapp/static/media/CircularSpUIv3T-Book.3466e0ec02233312a508.woff2 -> /usr/share/qt-superbird-app/static/media/CircularSpUIv3T-Book.3466e0ec02233312a508.woff2
push: webapp/static/media/CircularSpUIv3T-Bold.8d0a45ccf7017ce6c399.woff2 -> /usr/share/qt-superbird-app/static/media/CircularSpUIv3T-Bold.8d0a45ccf7017ce6c399.woff2
push: webapp/static/media/CircularSpUIv3T-Black.c21e63c579eddbb69e2b.woff2 -> /usr/share/qt-superbird-app/static/media/CircularSpUIv3T-Black.c21e63c579eddbb69e2b.woff2
push: webapp/index.html -> /usr/share/qt-superbird-app/index.html
push: webapp/asset-manifest.json -> /usr/share/qt-superbird-app/asset-manifest.json
24 files pushed. 0 files skipped.
7454 KB/s (9679209 bytes in 1.268s)

C:\carthing\carthing-non-premium-spotify>adb shell reboot


I didn't notice that the command have pushed the files to the wrong folder, so just double check the output result of push command to make sure those files are in right place.
